### ISSUE TITLE
invalid id error while using sendPing

### ISSUE THREAD

**Issue by prerna79** [mozilla-rally/study-template#35]
Error details: background.js:1418 Rally.sendPing - error while sending geolocation TypeError: Error in invocation of runtime.sendMessage(optional string extensionId, any message, optional object options, optional function responseCallback): Invalid extension id: 'rally-core@mozilla.org' 

PS: I'm using the default keys that are already there in the code to initialize rally.

**Comment by Dexterp37** [comment]
Hi @prerna79 ! Thank you for reporting this.

The problem you're seeing is due to the study trying to talk to the Rally Core Add-on. Unfortunately, even if it would be installed, the core add-on would not know about your addon and will not allow any communication.

To develop your study, you can safely ignore these errors for the moment.

We're currently working on a "developer mode" for the study template (#16 ) to make it happen.
